#!/bin/bash
echo "compiling"
nasm -f bin bootloader/kiminoMBR.s -o bin/KBL.boot

nasm -f bin bootloader/kiminoboot.s -o bin/KiminoPartBoot

cat bin/KBL bin/KiminoPartBoot > bin/KiminoBoot

echo "cat bin/KiminoBoot \{your_kernel\} > \{OS.iso\} to get your final image" 
